---
- name: Copy contents of dotfiles to machine
  copy:
    src: "../{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
  with_items: "{{ copy_items }}"

- name: Configure git a bit
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items: "{{ git_config_items }}"
