---
- name: Ensure appropriate directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items: "{{ dirs_to_create }}"

- name: Copy contents of dotfiles to machine
  copy:
    src: "../{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    backup: true
  with_items: "{{ copy_items }}"

- name: Configure git a bit
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items: "{{ git_config_items }}"
