---
pythons:
  - python3
  - python3-pip
  - python3.10

_always_pips:
  - pytest
_home_pips:
  - numpy
  - scipy
  - pandas
pips: "{{ _always_pips if not at_home|bool else _always_pips|union(_home_pips) }}"
