#!/usr/bin/zsh

# Just a handful of commands that are only for when I'm on my work computer

# gvm pkgset use storreduce > /dev/null
# Want to set up a few named directories to get into the git repos
ir=~/ir-bpreskitt
: ~ir
/usr/bin/ssh-add ~/.ssh/id_pure_root

export PYTHONDONTWRITEBYTECODE=1

triage-get () {
  local WHEREVER_YOU_TRIAGE="/tmp"
  pushd ${WHEREVER_YOU_TRIAGE}
  triage build $1 artifacts --fetch --no-all-blades --no-binary
  echo "(Subdirectory of ${WHEREVER_YOU_TRIAGE})"
  popd
}

function git-remote-add {
  local username="$1"
  git remote add ${username} ssh://git@stash-ir.dev.purestorage.com:7999/ir/${username}.git
  git remote set-url --push ${username} NO_PUSHING_ALLOWED
  git fetch ${username}
}
