---
copy_items:
  - zshrc
  - zsh_aliases
  - gitignore_global
  - tmux.conf
  - oh-my-zsh/
  - emacs.d/
  - config/

dirs_to_create:
  - "{{ ansible_user_dir }}/.emacs.d/lisp/themes"
  - "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/my-emacs"

git_config_items:
  - name: user.name
    value: "Brian Preskitt"
  - name: user.email
    value: "{{ 'bppresk@outlook.com' if at_home|bool else 'bpreskitt@purestorage.com' }}"
  - name: core.excludesfile
    value: "{{ ansible_user_dir }}/.gitignore_global"
  - name: core.editor
    value: "emacsclient -a=\"emacs -nw\""
  - name: core.pager
    value: "delta"
  - name: interactive.diffFilter
    value: "delta --color-only"
