---
- name: Gather package facts
  package_facts:
    manager: auto

- name: Install home packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ home_debs }}"
  when: at_home|bool

- name: Install universal packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ always_debs }}"

- name: Download downloaded packages
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.deb"
  with_items: "{{ downloaded_debs }}"
  when: at_home|bool and not item.name in ansible_facts.packages

- name: Install downloaded packages
  become: yes
  command: apt install -y --fix-broken "/tmp/{{ item.name }}.deb"
  with_items: "{{ downloaded_debs }}"
  when: at_home|bool and not item.name in ansible_facts.packages

- name: Remove downloaded packages
  when: at_home|bool
  file:
    state: absent
    path: "/tmp/{{ item.name }}.deb"
  with_items: "{{ downloaded_debs }}"

- name: Install oh my zsh
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Set default shell as zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Add special keys
  become: yes
  apt_key:
    url: "{{ item.key }}"
  with_items: "{{ special_packages }}"
  when: at_home|bool

- name: Add special repos
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
  with_items: "{{ special_packages }}"
  when: at_home|bool

- name: Install special-repo packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ item.name }}"
  with_items: "{{ special_packages }}"
  ignore_errors: "{{ansible_check_mode}}"

# For the emacs stuff, I'm using a special emacs repo at
# https://launchpad.net/~kelleyk/+archive/ubuntu/emacs Key id is under
# "Adding this PPA to your system"
- name: Add emacs key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 873503A090750CDAEB0754D93FF0E01EEAAFC9CD

- name: Add emacs repo
  become: yes
  vars:
    release: "{{ 'bionic' if ansible_distribution == 'Linux Mint' else ansible_distribution_release }}"
  apt_repository:
    repo: "deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu {{ release }} main"
    filename: kelleyk_emacs

- name: Install emacs
  become: yes
  apt:
    update_cache: yes
    name: "{{ 'emacs26' if at_home|bool else 'emacs25' }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add latest melpa key
  shell: gpg --keyserver keys.gnupg.net --homedir ~/.emacs.d/elpa/gnupg --recv-keys 066DAFCB81E42C40
