---
- name: Configure machine
  hosts: all
  become_method: sudo
  gather_facts: yes
  roles:
    - role: base
    - role: python
    - role: unpack_dots
    - role: home
      when: at_home|bool
    - role: get_code
      when: on_pure_vm
    
