---
- name: Common packages and configuration
  hosts: all
  gather_facts: yes
  roles:
    - role: common_packages
    - role: common_comfort
    - role: python
    - role: unpack_dots

- name: Additional packages and config for home computers
  hosts: home
  gather_facts: yes
  roles:
    - role: home_comfort

- name: Configure the dnsmasq base server
  hosts: home_servers
  roles:
    - role: server_config

- name: Configure the non-server computers
  hosts: home_clients
  roles:
    - role: client_config
