---
- name: Python | Install python
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ pythons }}"

- name: Python | Install python packages
  when: false
  become: yes
  pip:
    executable: pip3
    name: "{{ pips }}"
