---
- name: Python | Install python
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ pythons }}"

- name: Python | Install python packages
  become: yes
  pip:
    executable: pip3
    name: "{{ pips }}"

# - name: Python | Create directory for virtual environment
#   become: yes
#   file:
#     path: /usr/local/share/py3.5-venv
#     state: directory
#     owner: "{{ ansible_user_id }}"
  
# - name: Python | Create virtual environment
#   shell: python3.5 -m venv /usr/local/share/py3.5-venv
#   when: on_pure_vm|bool
