---
home_debs:
  - adb
  - dnsmasq
  - ffmpeg
  - firefox
  - gimp
  - octave
  - openvpn
  - skypeforlinux
  - steam
  - telegram-desktop
  - texlive-full
  - thunderbird
  - transmission
  - vpnc
  - xkcdpass

downloaded_debs:
  - name: discord
    url: "https://discordapp.com/api/download?platform=linux&format=deb"
  - name: slack-desktop
    url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.0-amd64.deb"
  - name: zoom
    url: "https://zoom.us/client/latest/zoom_amd64.deb"

special_packages:
  - syncthing:
    name: syncthing
    repo: deb https://apt.syncthing.net/ syncthing stable
    key: https://syncthing.net/release-key.txt
  - spotify:
    name: spotify-client
    repo: deb http://repository.spotify.com stable non-free
    key: https://download.spotify.com/debian/pubkey.gpg
  - signal:
    name: signal-desktop
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    key: https://updates.signal.org/desktop/apt/keys.asc

misc_home_dir: "../misc-home"

misc_copy_items:
  - usr/local/bin
  - usr/local/share