---
- name: Disable and stop systemd-resolved
  become: yes
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: Enable and start dnsmasq
  become: yes
  systemd:
    name: dnsmasq
    enabled: true
    state: started

- name: Use /etc/resolv.conf, rather than output of resolvconf
  become: yes
  lineinfile:
    path: /etc/default/dnsmasq
    regexp: '^#?IGNORE_RESOLVCONF='
    state: present
    line: 'IGNORE_RESOLVCONF=yes'
  notify: Restart dnsmasq

- name: Turn off the vpn
  become: yes
  command: pkill vpn

- name: Add local nameserver to /etc/resolv.conf
  become: yes
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 127.0.0.53"
    state: present

- name: Make syncthing start automatically
  become: yes
  systemd:
    name: syncthing
    scope: user
    enabled: yes
    state: started