---
- name: Install universal packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ always_debs }}"

- name: Install oh my zsh
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Set default shell as zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

# For the emacs stuff, I'm using a special emacs repo at
# https://launchpad.net/~kelleyk/+archive/ubuntu/emacs Key id is under
# "Adding this PPA to your system"
- name: Add emacs key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 873503A090750CDAEB0754D93FF0E01EEAAFC9CD

- name: Add emacs repo
  become: yes
  vars:
    release: "{{ 'bionic' if ansible_distribution == 'Linux Mint' else ansible_distribution_release }}"
  apt_repository:
    repo: "deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu {{ release }} main"
    filename: kelleyk_emacs

- name: Install emacs
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    update_cache: yes
    name: "{{ 'emacs26' if at_home|bool else 'emacs25' }}"

- name: Add latest melpa key
  command: gpg --keyserver keyserver.ubuntu.com --homedir ~/.emacs.d/elpa/gnupg --recv-keys 066DAFCB81E42C40
  register: output
  # The first line of output (which goes to stderr) says "not changed"
  # if the key was already there.
  changed_when: not output.stderr | regex_search('not changed')
